config/routes.rb
get  'projects/:project_id/toubans',             :to => 'toubans#index'
get  'projects/:project_id/toubans/new',         :to => 'toubans#new'
post 'projects/:project_id/toubans/new',         :to => 'toubans#new'
get  'projects/:project_id/toubans/:id',         :to => 'toubans#show'
get  'projects/:project_id/toubans/:id/edit',    :to => 'toubans#edit'
post 'projects/:project_id/toubans/:id/edit',    :to => 'toubans#edit'
post 'projects/:project_id/toubans/:id/destroy', :to => 'toubans#destroy'
post 'projects/:project_id/toubans/:id/prev',    :to => 'toubans#prev'
post 'projects/:project_id/toubans/:id/next',    :to => 'toubans#next'

app/models/touban.rb
class Touban < ActiveRecord::Base
  include Redmine::SafeAttributes

  belongs_to :project
  has_many :touban_users, :dependent => :destroy
  has_many :users, :through => :touban_users, :source => :user

  serialize :tasks # 配列として保存

  safe_attributes :name, :description, :tasks, :step, :user_ids

  validates_presence_of :name, :project, :tasks, :step

  # 今日の当番の組み合わせ
  def today_touban
    return @today_touban if @today_touban

    @today_touban = []
    user_index = self.touban_index
    user_count = self.users.length
    self.tasks.each do |task|
      next if task.blank? # 空行には割り当てない
      @today_touban << [self.users[user_index], task]
      user_index = (user_index + 1) % user_count
    end

    return @today_touban
  end

  # 今日の当番ユーザ
  def today_users
    return @today_users if @today_users

    # 最後のユーザを越えるなら、ループさせる
    touban_count = self.tasks.length
    if (self.touban_index + touban_count) > self.users.count
      over = self.touban_index + touban_count - self.users.count
      @today_users = self.users[self.touban_index, (touban_count - over)] + self.users[0, over]
      @today_users.uniq!
    else
      @today_users = self.users[self.touban_index, touban_count]
    end

    return @today_users
  end

  # 当番を前に戻す
  def prev_touban
    @today_touban = nil
    @today_users = nil
    user_count = self.users.count
    self.touban_index = (self.touban_index + user_count - self.step) % user_count
  end

  def prev_touban!
    self.prev_touban
    self.save
  end

  # 当番を次に進める
  def next_touban
    @today_touban = nil
    @today_users = nil
    self.touban_index = (self.touban_index + self.step) % self.users.count
  end

  def next_touban!
    self.next_touban
    self.save
  end

  private
  def validate
    if self.step == 0
      self.errors.add(:step, :invalid)
    end
  end
end

app/models/touban_user.rb
class ToubanUser < ActiveRecord::Base
  include Redmine::SafeAttributes

  belongs_to :touban
  belongs_to :user

  safe_attributes :user_id, :touban_id

  acts_as_list :scope => :touban_id # リスト
end

app/controllers/toubans_controller.rb
class ToubansController < ApplicationController
  menu_item :touban

  before_filter :find_project_by_project_id
  before_filter :authorize
  before_filter :find_touban, :only => [:show, :edit, :destroy, :prev, :next]

  # 一覧
  def index
    @toubans = Touban.find_all_by_project_id(@project.id)
  end

  # 詳細
  def show
  end

  # 新規
  def new
    @touban = Touban.new
    @touban.project = @project

    if request.post? && params[:touban]
      params[:touban][:tasks] = params[:touban][:tasks].split(/\r?\n/) if params[:touban][:tasks]
      @touban.safe_attributes = params[:touban]
      if @touban.save
        redirect_to  :controller => 'toubans', :action => 'index', :project_id => @project
#        redirect_to :controller => 'toubans', :action => 'show', :id => @touban.id, :project_id => @project
      end
    end
  end

  # 編集
  def edit
    if request.post? && params[:touban]
      params[:touban][:tasks] = params[:touban][:tasks].split(/\r?\n/) if params[:touban][:tasks]
      @touban.safe_attributes = params[:touban]
      if @touban.save
        redirect_to  :controller => 'toubans', :action => 'index', :project_id => @project
#        redirect_to :controller => 'toubans', :action => 'show', :id => @touban.id, :project_id => @project
      end
    end
  end

  # 削除
  def destroy
    @touban.destroy
    redirect_to  :controller => 'toubans', :action => 'index', :project_id => @project
  end

  # 当番を1つ前に戻す
  def prev
    @touban.prev_touban!
    redirect_to  :controller => 'toubans', :action => 'index', :project_id => @project
  end

  # 当番を次に進める
  def next
    @touban.next_touban!
    redirect_to  :controller => 'toubans', :action => 'index', :project_id => @project
  end

  private
  # 当番情報を取得
  def find_touban
    render_404 unless params[:id]
    @touban = Touban.find_by_id(params[:id])
    render_404 unless @touban
  end
end

app/helpers/toubans_helper.rb
module ToubansHelper
  def touban_users(touban)
    return ''
  end
end

app/views/toubans/_form.html.erb
<%= error_messages_for 'touban' %>

<% content_for :header_tags do %>
<%= javascript_include_tag 'select_list_move' %>
<% end %>

<div class="box tabular">
  <p>
    <label><%= l(:field_name) %><span class="required">*</span></label>
    <%= text_field_tag('touban[name]', @touban.name, :size => 50) %>
  </p>

  <p>
    <label><%= l(:field_description) %></label>
    <%= text_area_tag('touban[description]', @touban.description, :cols => 80, :rows => 5) %>
  </p>

  <table>
    <tbody>
      <tr>
        <td style="width: 170px; font-weight: bold; text-align: right;"><%= l(:field_user) %></td>
        <td>
          <small><%= l(:field_touban_members) %></small><br />
          <%= select_tag('project_members',
                         options_for_select((@project.principals - @touban.users).collect{|p| [p.name, p.id.to_s]}),
                         :multiple => true, :style => 'width: 150px; height: 100px;') %>
        </td>
        <td>
          <%= button_to_function(raw('&#8594;'), 'moveOptions(this.form.project_members, this.form.touban_user_ids);') %><br />
          <%= button_to_function(raw('&#8592;'), 'moveOptions(this.form.touban_user_ids, this.form.project_members);') %><br />
        </td>
        <td>
          <small><%= l(:field_touban_users) %></small><br />
          <%= select_tag('touban[user_ids]',
                         options_for_select(@touban.users.collect{|u| [u.name, u.id.to_s]}),
                         :multiple => true, :style => 'width: 150px; height: 100px;') %>
        </td>
        <td>
          <%= button_to_function(raw('&#8593;'), 'moveOptionUp(this.form.touban_user_ids);') %><br />
          <%= button_to_function(raw('&#8595;'), 'moveOptionDown(this.form.touban_user_ids);') %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td colspan="4"><small><%= l(:notice_touban_users) %></small</td>
      </tr>
    </tbody>
  </table>

  <p>
    <label><%= l(:field_touban_tasks) %><span class="required">*</span></label>
    <%= text_area_tag('touban[tasks]', (@touban.tasks || []).join("\n"), :cols => 50, :rows => 5) %>
    <br /><small><%= l(:notice_touban_tasks) %></small>
  </p>

  <p>
    <label><%= l(:field_touban_step) %><span class="required">*</span></label>
     <%= text_field_tag('touban[step]', @touban.step, :size => 4) %>
     <br /><small><%= l(:notice_touban_step) %></small>
  </p>
</div>

<%= wikitoolbar_for 'touban_description' %>

app/views/toubans/add_member.html.erb
<h2>ToubansController#add_member</h2>

app/views/toubans/destroy.html.erb
<h2>ToubansController#destroy</h2>

app/views/toubans/edit.html.erb
<h2>
  <%= link_to(l(:label_touban), {:controller => 'toubans', :action => 'index', :project_id => @project}) %>
  &#187;
  <%= link_to(@touban.name, {:controller => 'toubans', :action => 'show', :project_id => @project, :id => @touban.id}) %>
  &#187;
  <%= l(:button_edit) %>
</h2>

<%= form_tag({:controller => 'toubans', :action => 'edit', :id => @touban.id, :project_id => @project}) do %>
  <%= render(:partial => 'toubans/form') %>

  <%= button_to_function(l(:button_update), "selectAllOptions('touban_user_ids'); form.submit();") %>
<% end %>

app/views/toubans/index.html.erb
<div class="contextual">
  <%= link_to(l(:label_touban_new), {:controller => 'toubans', :action => 'new', :project_id => @project}, :class => 'icon icon-add') %>
</div>

<h2><%= l(:label_touban) %></h3>

<table class="list" style="width: auto;">
<thead>
  <tr>
    <th><%= l(:field_name) %></th>
    <th style="width: 30%;"><%= l(:field_description) %></th>
    <th><%= l(:field_touban_user) %></th>
    <th style="width: 36px;"></th>
    <th class="buttons"></th>
  </tr>
</thead>
<tbody>
<% @toubans.each do |touban| %>
  <tr class="<%= cycle('even', 'odd') %>">
    <td><%= touban.name %></td>
    <td><%= textilizable(touban, :description) %></td>
    <td><%= raw touban.today_touban.collect{|t| "<span style='font-weight: bold;'>#{h(t[1])}</span> - #{h(t[0])}"}.join('<br />') %></tD>
    <td style="text-align: center; width: 36px;">
      <%= link_to(image_tag('1uparrow.png'),
                            {:controller => 'toubans', :action => 'prev', :id => touban.id, :project_id => @project},
                            :title => l(:text_touban_prev), :method => 'post') %>
      <%= link_to(image_tag('1downarrow.png'),
                            {:controller => 'toubans', :action => 'next', :id => touban.id, :project_id => @project},
                            :title => l(:text_touban_next), :method => 'post') %>
    </td>
    <td class="buttons">
      <%= link_to(l(:button_edit),
                  {:controller => 'toubans', :action => 'edit', :project_id => @project, :id => touban.id},
                   :class => 'icon icon-edit') %>
      <%= link_to(l(:button_delete),
                  {:controller => 'toubans', :action => 'destroy', :project_id => @project, :id => touban.id},
                   :class => 'icon icon-del', :method => 'post',
                   :confirm => l(:text_are_you_sure)) %>
    </td>
  </tr>
<% end %>
<% reset_cycle %>
</tbody>
</table>

<% html_title("#{@project.name} - #{l(:label_touban)}") %>

app/views/toubans/new.html.erb
<h2>
  <%= link_to(l(:label_touban), {:controller => 'toubans', :action => 'index', :project_id => @project}) %>
  &#187;
  <%= l(:label_touban_new) %>
</h2>

<%= form_tag({:controller => 'toubans', :action => 'new', :project_id => @project}) do %>
  <%= render(:partial => 'toubans/form') %>

  <%= button_to_function(l(:button_create), "selectAllOptions('touban_user_ids'); form.submit();") %>
<% end %>

app/views/toubans/remove_member.html.erb
<h2>ToubansController#remove_member</h2>

app/views/toubans/show.html.erb
<h2>
  <%= link_to(l(:label_touban), {:controller => 'toubans', :action => 'index', :project_id => @project}) %>
  &#187;
  <%= @touban.name %>
</h2>

<div class="box tabular">
  <p>
    <label><%= l(:field_name) %></label>
    <%= @touban.name %>
  </p>

  <p>
    <label><%= l(:field_touban_users) %></label>
    <%= raw @touban.users.collect{|u| h(u.name)}.join('<br />') %>
  </p>

  <p>
    <label><%= l(:field_touban_tasks) %></label>
     <%= raw h(@touban.tasks).gsub(/\r?\n/, '<br />') %>
  </p>

  <p>
    <label><%= l(:field_touban_step) %></label>
    <%= @touban.step %>
  </p>

  <h4><%= l(:field_description) %></h4>
  <%= textilizable(@touban, :description) %>
</div>